name: Run admin.py

on:
  schedule:
    - cron: '30 16 * * *'  # 每天下午 16 点 30 分（即北京时间凌晨 0 点 30 分）
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新到 v3

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新到 v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
